server:
  port: 8084
  servlet:
    context-path: /card-service

spring:
  application:
    name: card_service
  datasource:
    url: "jdbc:mysql://localhost:3306/bank_account_transaction"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Kieuhieu2@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

