server:
  port: 8083
  servlet:
    context-path: /account-service

spring:
  application:
    name: account_service
  datasource:
    url: "jdbc:mysql://localhost:3306/bank_account_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Kieuhieu2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

# Cấu hình Keycloak
keycloak:
  realm: bank_account
  auth-server-url: http://localhost:9080
  resource: klb
  credentials:
    secret: qzmX9MnaaNsm37yvDdIqYIPwhu4nrYNy

app:
  services:
    profile: http://localhost:8081/profile